services:
  PostgreSQL:
    image: postgres:latest
    container_name: PostgreSQL
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
